const presets = {
  greek_alphabet: {
    label: "Greek alphabet",
    lines: [
      "alpha", "beta", "gamma", "delta", "epsilon", "zeta",
      "eta", "theta", "iota", "kappa", "lambda", "mu",
      "nu", "xi", "omicron", "pi", "rho", "sigma",
      "tau", "upsilon", "phi", "chi", "psi", "omega",
    ],
    index: [
      "Α", "Β", "Γ", "Δ", "Ε", "Ζ", "Η", "Θ", "Ι", "Κ", "Λ", "Μ",
      "Ν", "Ξ", "Ο", "Π", "Ρ", "Σ", "Τ", "Υ", "Φ", "Χ", "Ψ", "Ω",
    ],
  },
  months: {
    label: "Months of the year",
    lines: [
      "January", "February", "March",
      "April", "May", "June",
      "July", "August", "September",
      "October", "November", "December",
    ],
  },
  solar_system: {
    label: "Planets from the Sun",
    lines: [
      "Mercury",
      "Venus",
      "Earth",
      "Mars",
      "Jupiter",
      "Saturn",
      "Uranus",
      "Neptune",
      "Pluto",
    ],
  },
  english_alphabet: {
    label: "English alphabet",
    lines: [
      "A","B","C","D","E","F","G","H","I","J","K","L","M",
      "N","O","P","Q","R","S","T","U","V","W","X","Y","Z",
    ],
  },

  hebrew_alphabet: {
    label: "Hebrew alphabet",
    lines: [
      "aleph","bet","gimel","dalet","he","vav","zayin","het","tet",
      "yod","kaf","lamed","mem","nun","samekh","ayin","pe","tsadi",
      "qof","resh","shin","tav",
    ],
    index: [
      "א","ב","ג","ד","ה","ו","ז","ח","ט",
      "י","כ","ל","מ","נ","ס","ע","פ","צ",
      "ק","ר","ש","ת",
    ],
  },

  zodiac: {
    label: "Zodiac signs",
    lines: [
      "Aries","Taurus","Gemini","Cancer","Leo","Virgo",
      "Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces",
    ],
    index: [
      "♈","♉","♊","♋","♌","♍",
      "♎","♏","♐","♑","♒","♓",
    ],
  },
  tarot_major_arcana: {
    label: "Tarot major arcana",
    lines: [
      "The Fool",
      "The Magician",
      "The High Priestess",
      "The Empress",
      "The Emperor",
      "The Hierophant",
      "The Lovers",
      "The Chariot",
      "Strength",
      "The Hermit",
      "Wheel of Fortune",
      "Justice",
      "The Hanged Man",
      "Death",
      "Temperance",
      "The Devil",
      "The Tower",
      "The Star",
      "The Moon",
      "The Sun",
      "Judgement",
      "The World",
    ],
    index: [
      "0","I","II","III","IV","V","VI","VII","VIII","IX",
      "X","XI","XII","XIII","XIV","XV","XVI","XVII","XVIII","XIX","XX","XXI",
    ],
  },

  morse_code: {
    label: "Morse code (A–Z)",
    lines: [
      ".-","-...","-.-.","-..",".","..-.","--.","....","..",".---",
      "-.-",".-..","--","-.","---",".--.","--.-",".-.","...","-",
      "..-","...-",".--","-..-","-.--","--..",
    ],
    index: [
      "A","B","C","D","E","F","G","H","I","J",
      "K","L","M","N","O","P","Q","R","S","T",
      "U","V","W","X","Y","Z",
    ],
  },

  song_lyrics: {
    label: "Song lyrics",
    lines: [
      "Never","gonna","give","you","up",
      "Never","gonna","let","you","down",
      "Never","gonna","run","around",
      "And","desert","you",
    ],
  },
};

const presetSelect = document.getElementById("presetSelect");
const delayInput = document.getElementById("delayInput");
const delayOutput = document.getElementById("delayOutput");
const orderModeSelect = document.getElementById("orderModeSelect");
const linesInput = document.getElementById("linesInput");
const useIndexInput = document.getElementById("useIndexInput");
const indexPanel = document.getElementById("indexPanel");
const indexModeSelect = document.getElementById("indexModeSelect");
const indexInput = document.getElementById("indexInput");
const sequenceMeta = document.getElementById("sequenceMeta");
const playButton = document.getElementById("playButton");
const controlPanel = document.getElementById("controlPanel");
const playbackScreen = document.getElementById("playbackScreen");
const sequencePair = document.getElementById("sequencePair");
const sequenceIndex = document.getElementById("sequenceIndex");
const sequenceLine = document.getElementById("sequenceLine");
const playbackMeta = document.getElementById("playbackMeta");
const stopButton = document.getElementById("stopButton");

let playbackFrames = [];
let currentFrameIndex = 0;
let playbackTimer = null;
let isPaused = false;
let indexWasAutoGenerated = false;

function populatePresets() {
  for (const [key, preset] of Object.entries(presets)) {
    const option = document.createElement("option");
    option.value = key;
    option.textContent = preset.label;
    presetSelect.append(option);
  }
}

function updateDelayLabel() {
  delayOutput.value = `${delayInput.value} ms`;
  delayOutput.textContent = delayOutput.value;
}

function splitTextareaLines(value) {
  return value
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
}

function getMainLines() {
  return splitTextareaLines(linesInput.value);
}

function getIndexLines() {
  return splitTextareaLines(indexInput.value);
}

function buildAutoIndex(lines) {
  return lines.map((_, index) => String(index + 1));
}

function syncIndexVisibility() {
  indexPanel.classList.toggle("hidden", !useIndexInput.checked);
}

function syncIndexDefaults(force = false) {
  if (!useIndexInput.checked) {
    return;
  }

  const autoIndex = buildAutoIndex(getMainLines());
  const autoIndexText = autoIndex.join("\n");

  if (force || indexWasAutoGenerated || getIndexLines().length === 0) {
    indexInput.value = autoIndexText;
    indexWasAutoGenerated = true;
  }
}

function buildOrder(length, mode) {
  const order = Array.from({ length }, (_, index) => index);

  if (mode === "reverse") {
    return order.reverse();
  }

  if (mode === "random") {
    for (let index = order.length - 1; index > 0; index -= 1) {
      const swapIndex = Math.floor(Math.random() * (index + 1));
      [order[index], order[swapIndex]] = [order[swapIndex], order[index]];
    }
  }

  return order;
}

function getPreparedSequence() {
  const lines = getMainLines();
  const usesIndex = useIndexInput.checked;
  const indexLines = usesIndex ? getIndexLines() : [];
  const orderMode = orderModeSelect.value;

  if (lines.length === 0) {
    return { valid: false, reason: "Add at least one line to play." };
  }

  if (usesIndex && indexLines.length !== lines.length) {
    return {
      valid: false,
      reason: `Index has ${indexLines.length} lines, but main list has ${lines.length}.`,
    };
  }

  const orderedIndexes = buildOrder(lines.length, orderMode);
  const orderedPairs = orderedIndexes.map((index) => ({
    line: lines[index],
    index: usesIndex ? indexLines[index] : null,
  }));

  return {
    valid: true,
    lines,
    indexLines,
    usesIndex,
    orderedPairs,
  };
}

function buildPlaybackFrames(preparedSequence) {
  if (!preparedSequence.usesIndex) {
    return preparedSequence.orderedPairs.map((pair) => ({
      kind: "single",
      line: pair.line,
      index: "",
    }));
  }

  const indexMode = indexModeSelect.value;

  if (indexMode === "alongside") {
    return preparedSequence.orderedPairs.map((pair) => ({
      kind: "alongside",
      line: pair.line,
      index: pair.index,
    }));
  }

  if (indexMode === "before") {
    return preparedSequence.orderedPairs.flatMap((pair) => [
      {
        kind: "index-only",
        line: "",
        index: pair.index,
      },
      {
        kind: "single",
        line: pair.line,
        index: "",
      },
    ]);
  }

  return preparedSequence.orderedPairs.flatMap((pair) => [
    {
      kind: "single",
      line: pair.line,
      index: "",
    },
    {
      kind: "index-only",
      line: "",
      index: pair.index,
    },
  ]);
}

function updateSequenceMeta() {
  const preparedSequence = getPreparedSequence();

  if (!preparedSequence.valid) {
    sequenceMeta.textContent = preparedSequence.reason;
    playButton.disabled = true;
    return;
  }

  if (preparedSequence.usesIndex) {
    const frameCount =
      indexModeSelect.value === "alongside"
        ? preparedSequence.orderedPairs.length
        : preparedSequence.orderedPairs.length * 2;
    const pairNoun = preparedSequence.orderedPairs.length === 1 ? "pair" : "pairs";
    const frameNoun = frameCount === 1 ? "frame" : "frames";
    sequenceMeta.textContent = `${preparedSequence.orderedPairs.length} ${pairNoun} ready, ${frameCount} ${frameNoun} in playback`;
  } else {
    const noun = preparedSequence.lines.length === 1 ? "line" : "lines";
    sequenceMeta.textContent = `${preparedSequence.lines.length} ${noun} ready`;
  }

  playButton.disabled = false;
}

function loadPreset(key) {
  if (key === "custom") {
    return;
  }

  const preset = presets[key];
  if (!preset) {
    return;
  }

  linesInput.value = preset.lines.join("\n");

  if (preset.index) {
    useIndexInput.checked = true;
    indexModeSelect.value = "alongside";
    indexInput.value = preset.index.join("\n");
    indexWasAutoGenerated = false;
  } else if (useIndexInput.checked) {
    syncIndexDefaults(true);
  }

  syncIndexVisibility();
  updateSequenceMeta();
}

function renderFrame(frame) {
  sequencePair.classList.remove("mode-single", "mode-alongside");
  sequenceIndex.classList.add("hidden");
  sequenceLine.classList.add("hidden");

  if (frame.kind === "alongside") {
    sequencePair.classList.add("mode-alongside");
    sequenceIndex.textContent = frame.index;
    sequenceLine.textContent = frame.line;
    sequenceIndex.classList.remove("hidden");
    sequenceLine.classList.remove("hidden");
    return;
  }

  sequencePair.classList.add("mode-single");

  if (frame.kind === "index-only") {
    sequenceIndex.textContent = frame.index;
    sequenceIndex.classList.remove("hidden");
    return;
  }

  sequenceLine.textContent = frame.line;
  sequenceLine.classList.remove("hidden");
}

function updatePlaybackMeta() {
  playbackMeta.textContent = `${currentFrameIndex + 1} / ${playbackFrames.length} at ${delayInput.value} ms`;
}

function showCurrentFrame() {
  renderFrame(playbackFrames[currentFrameIndex]);
  updatePlaybackMeta();
}

function clearPlaybackTimer() {
  if (playbackTimer) {
    window.clearInterval(playbackTimer);
    playbackTimer = null;
  }
}

function stopPlayback() {
  clearPlaybackTimer();
  isPaused = false;
  playbackScreen.classList.add("hidden");
  controlPanel.classList.remove("hidden");
  document.body.classList.remove("is-playing");
}

function stepSequence() {
  currentFrameIndex += 1;

  if (currentFrameIndex >= playbackFrames.length) {
    stopPlayback();
    return;
  }

  showCurrentFrame();
}

function startPlaybackTimer() {
  clearPlaybackTimer();
  playbackTimer = window.setInterval(stepSequence, Number(delayInput.value));
}

function startPlayback() {
  const preparedSequence = getPreparedSequence();
  if (!preparedSequence.valid) {
    updateSequenceMeta();
    return;
  }

  playbackFrames = buildPlaybackFrames(preparedSequence);
  currentFrameIndex = 0;
  isPaused = false;
  controlPanel.classList.add("hidden");
  playbackScreen.classList.remove("hidden");
  document.body.classList.add("is-playing");
  showCurrentFrame();
  startPlaybackTimer();
}

function togglePause() {
  if (playbackScreen.classList.contains("hidden")) {
    return;
  }

  if (isPaused) {
    isPaused = false;
    showCurrentFrame();
    startPlaybackTimer();
    return;
  }

  isPaused = true;
  clearPlaybackTimer();
  playbackMeta.textContent = `Paused on ${currentFrameIndex + 1} / ${playbackFrames.length}`;
}

function handleKeydown(event) {
  if (event.code === "Escape" && !playbackScreen.classList.contains("hidden")) {
    stopPlayback();
  }

  if (event.code === "Space" && !playbackScreen.classList.contains("hidden")) {
    event.preventDefault();
    togglePause();
  }
}

function markCustomAndUpdate() {
  presetSelect.value = "custom";
  updateSequenceMeta();
}

presetSelect.addEventListener("change", (event) => {
  loadPreset(event.target.value);
});

delayInput.addEventListener("input", () => {
  updateDelayLabel();

  if (!playbackScreen.classList.contains("hidden") && !isPaused) {
    showCurrentFrame();
    startPlaybackTimer();
  }
});

orderModeSelect.addEventListener("change", markCustomAndUpdate);

linesInput.addEventListener("input", () => {
  presetSelect.value = "custom";
  if (useIndexInput.checked && indexWasAutoGenerated) {
    syncIndexDefaults(true);
  }
  updateSequenceMeta();
});

useIndexInput.addEventListener("change", () => {
  presetSelect.value = "custom";
  syncIndexVisibility();
  if (useIndexInput.checked) {
    syncIndexDefaults(true);
  }
  updateSequenceMeta();
});

indexModeSelect.addEventListener("change", () => {
  presetSelect.value = "custom";
  updateSequenceMeta();
});

indexInput.addEventListener("input", () => {
  presetSelect.value = "custom";
  indexWasAutoGenerated = false;
  updateSequenceMeta();
});

playButton.addEventListener("click", startPlayback);
stopButton.addEventListener("click", stopPlayback);
window.addEventListener("keydown", handleKeydown);

populatePresets();
updateDelayLabel();
syncIndexVisibility();
loadPreset("greek_alphabet");
presetSelect.value = "greek_alphabet";
updateSequenceMeta();
